#!/usr/bin/env node

const fetch = require('node-fetch');

fetch(
  `https://api.cloudflare.com/client/v4/zones/${process.env.CF_ZONE_ID}/purge_cache`,
  {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.CF_API_TOKEN}`
    },
    body: JSON.stringify({ purge_everything: true })
  }
)
  .then(res => res.json())
  .then(res => {
    if (!res.success) {
      console.log(res.errors);
      process.exit();
    } else {
      console.log(res);
    }
  });
