name: Danger

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-firebase:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Build Application
        run: yarn build
      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:covid-19-cnx
