name: Danger

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-deploy-firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn

      - name: Build Application

        run: |
          ./generate-env --env=${GITHUB_REF#refs/heads/}
          yarn build
        env:
          REACT_APP_SERVER: 'production'
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P ${GITHUB_REF#refs/heads/}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
